GET http://localhost:3000/employes


###
POST  http://localhost:3000/employes
Content-Type: application/json

{
    "name":"ambica",
    "age":"54"
}

###



PATCH      http://localhost:3000/employes/64034bf54d7724de705cc7aa


{
    "name":"jasmann singh",
    "age":"12",
}

###
DELETE http://localhost:3000/employes/64034bf54d7724de705c
